version: '3.4'
services:
  cleardb:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    image: db_anonymization
    env_file: ./secrets.env
    environment:
      ENV: "production"
    command: bundle exec ruby app/main.rb
