default: &default
  adapter: postgresql
  encoding: unicode
  pool: 40
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME_DEVELOPMENT'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
